# Autologin su tty1: la vera schermata di login e' il lock Quickshell (qs-lock.service).
# Riferimento: https://wiki.archlinux.org/title/Getty#Automatic_login_to_virtual_console
[Service]
ExecStart=
ExecStart=-/sbin/agetty -o '-p -f -- \\u' --noclear --autologin lemonademan %I $TERM
